sudo: required
services:
  - docker

before_install:
  - docker build -t streamlitapp -f Dockerfile .

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "us-east-2"
  app: "Testing-app"
  env: "Testingapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-822801770577"
  bucket_path: "Testing-app"
  on:
    branch: master

